build_docker: 
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - docker login -u $azure_registry_username -p $azure_registry_password fortiregistry.azurecr.io
    - ./build_docker.sh fortiregistry.azurecr.io $CI_COMMIT_TAG
