stages:
  - build
  - publish artifacts
  - vulncheck

services:
  - name: docker:28-dind
    alias: docker

build docker: 
  tags:
    - teampunkt
  stage: build
  rules:
    - if: '$CI_COMMIT_TAG'
  script:
    - export NAME=$(echo $CI_COMMIT_TAG | sed 's-/.*--')
    - export VERSION=$(echo $CI_COMMIT_TAG | sed 's-.*/--')
    - export IMAGE="fortiregistry.azurecr.io/$NAME:$VERSION"
    - docker login -u $azure_registry_username -p $azure_registry_password fortiregistry.azurecr.io
    - docker build -t "$IMAGE" -f "$NAME/build/package/Dockerfile" .
    - docker push "$IMAGE"


publish artifacts:
  tags:
    - teampunkt
  stage: publish artifacts
  rules:
    - if: "$CI_COMMIT_TAG =~ /^fortiup.*/"
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    paths:
      - "$CI_COMMIT_REF_SLUG"
  script:
    - export NAME=$(echo $CI_COMMIT_TAG | sed 's-/.*--')
    - export VERSION=$(echo $CI_COMMIT_TAG | sed 's-.*/--')
    - export IMAGE="fortiregistry.azurecr.io/$NAME:$VERSION"
    - docker login -u $azure_registry_username -p $azure_registry_password fortiregistry.azurecr.io
    - docker pull "$IMAGE"
    - docker run --rm --entrypoint cat "$IMAGE" "/usr/local/bin/$NAME" > $CI_COMMIT_REF_SLUG
    - chmod +x $CI_COMMIT_REF_SLUG


vulncheck:
  tags:
    - teampunkt
  stage: vulncheck
  script:
    - export IMAGE_NAME=$(echo "forti-vulncheck-$(cat /dev/urandom | tr -cd 'a-f0-9' | head -c 16)")
    - docker build -t "$IMAGE_NAME" -f .devcontainer/Dockerfile . # We use the devcontainer Dockerfile since it has all dependencies installed
    - docker run --rm --volume $PWD:/src:ro --workdir /src/ "$IMAGE_NAME" pwd
    - docker image rm "$IMAGE_NAME"
