services:
  - name: docker:24-dind
    alias: docker

build_docker: 
  tags:
    - teampunkt
  rules:
    - if: '$CI_COMMIT_TAG'
  artifacts:
    name: "$CI_COMMIT_REF_SLUG"
    paths:
      - "/$CI_COMMIT_REF_SLUG"
  script:
    - docker login -u $azure_registry_username -p $azure_registry_password fortiregistry.azurecr.io
    - export NAME=$(echo $CI_COMMIT_TAG | sed 's-/.*--')
    - export VERSION=$(echo $CI_COMMIT_TAG | sed 's-.*/--')
    - export IMAGE="fortiregistry.azurecr.io/$NAME:$VERSION"
    - docker build -t "$IMAGE" -f "$NAME/build/package/Dockerfile" .
    - docker push "$IMAGE"
    - if [ -f "/usr/local/bin/$NAME"]; then
          docker run --rm --entrypoint cat "$IMAGE" "/usr/local/bin/$NAME" > /$CI_COMMIT_REF_SLUG;
        fi
