name: Devcontainer image

on:
  workflow_dispatch:

jobs:
  devcontainer:
    name: Build and push devcontainer image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure Container Registry
        run: docker login -u ${{ secrets.AZURE_REGISTRY_USERNAME }} -p ${{ secrets.AZURE_REGISTRY_PASSWORD }} fortiregistry.azurecr.io

      - name: Build and push
        run: |
          docker build -t fortiregistry.azurecr.io/devcontainer:latest -f .devcontainer/Dockerfile .
          docker push fortiregistry.azurecr.io/devcontainer:latest
