// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: forecaster.proto

package internalprotocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Forecaster_GetForecast_FullMethodName = "/internalprotocol.Forecaster/GetForecast"
)

// ForecasterClient is the client API for Forecaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForecasterClient interface {
	GetForecast(ctx context.Context, in *GetForecastRequest, opts ...grpc.CallOption) (*Forecast, error)
}

type forecasterClient struct {
	cc grpc.ClientConnInterface
}

func NewForecasterClient(cc grpc.ClientConnInterface) ForecasterClient {
	return &forecasterClient{cc}
}

func (c *forecasterClient) GetForecast(ctx context.Context, in *GetForecastRequest, opts ...grpc.CallOption) (*Forecast, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Forecast)
	err := c.cc.Invoke(ctx, Forecaster_GetForecast_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForecasterServer is the server API for Forecaster service.
// All implementations must embed UnimplementedForecasterServer
// for forward compatibility.
type ForecasterServer interface {
	GetForecast(context.Context, *GetForecastRequest) (*Forecast, error)
	mustEmbedUnimplementedForecasterServer()
}

// UnimplementedForecasterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForecasterServer struct{}

func (UnimplementedForecasterServer) GetForecast(context.Context, *GetForecastRequest) (*Forecast, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForecast not implemented")
}
func (UnimplementedForecasterServer) mustEmbedUnimplementedForecasterServer() {}
func (UnimplementedForecasterServer) testEmbeddedByValue()                    {}

// UnsafeForecasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForecasterServer will
// result in compilation errors.
type UnsafeForecasterServer interface {
	mustEmbedUnimplementedForecasterServer()
}

func RegisterForecasterServer(s grpc.ServiceRegistrar, srv ForecasterServer) {
	// If the following call pancis, it indicates UnimplementedForecasterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Forecaster_ServiceDesc, srv)
}

func _Forecaster_GetForecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetForecastRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecasterServer).GetForecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Forecaster_GetForecast_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecasterServer).GetForecast(ctx, req.(*GetForecastRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Forecaster_ServiceDesc is the grpc.ServiceDesc for Forecaster service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Forecaster_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "internalprotocol.Forecaster",
	HandlerType: (*ForecasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetForecast",
			Handler:    _Forecaster_GetForecast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forecaster.proto",
}
