// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: forecaster.proto

package internalprotocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ForecastStatus int32

const (
	ForecastStatus_OK              ForecastStatus = 0
	ForecastStatus_OutsideAllGrids ForecastStatus = 1
	ForecastStatus_PointTooFarAway ForecastStatus = 2
)

// Enum value maps for ForecastStatus.
var (
	ForecastStatus_name = map[int32]string{
		0: "OK",
		1: "OutsideAllGrids",
		2: "PointTooFarAway",
	}
	ForecastStatus_value = map[string]int32{
		"OK":              0,
		"OutsideAllGrids": 1,
		"PointTooFarAway": 2,
	}
)

func (x ForecastStatus) Enum() *ForecastStatus {
	p := new(ForecastStatus)
	*p = x
	return p
}

func (x ForecastStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ForecastStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_forecaster_proto_enumTypes[0].Descriptor()
}

func (ForecastStatus) Type() protoreflect.EnumType {
	return &file_forecaster_proto_enumTypes[0]
}

func (x ForecastStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ForecastStatus.Descriptor instead.
func (ForecastStatus) EnumDescriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{0}
}

type GetForecastRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float32                `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Altitude      *Altitude              `protobuf:"bytes,3,opt,name=altitude,proto3" json:"altitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetForecastRequest) Reset() {
	*x = GetForecastRequest{}
	mi := &file_forecaster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetForecastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetForecastRequest) ProtoMessage() {}

func (x *GetForecastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetForecastRequest.ProtoReflect.Descriptor instead.
func (*GetForecastRequest) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{0}
}

func (x *GetForecastRequest) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *GetForecastRequest) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *GetForecastRequest) GetAltitude() *Altitude {
	if x != nil {
		return x.Altitude
	}
	return nil
}

type Altitude struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float32                `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	Override      bool                   `protobuf:"varint,2,opt,name=override,proto3" json:"override,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Altitude) Reset() {
	*x = Altitude{}
	mi := &file_forecaster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Altitude) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Altitude) ProtoMessage() {}

func (x *Altitude) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Altitude.ProtoReflect.Descriptor instead.
func (*Altitude) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{1}
}

func (x *Altitude) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Altitude) GetOverride() bool {
	if x != nil {
		return x.Override
	}
	return false
}

type Forecast struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ForecastStatus ForecastStatus         `protobuf:"varint,1,opt,name=forecastStatus,proto3,enum=internalprotocol.ForecastStatus" json:"forecastStatus,omitempty"`
	ForecastMeta   *ForecastMeta          `protobuf:"bytes,2,opt,name=forecastMeta,proto3" json:"forecastMeta,omitempty"`
	ParameterMeta  []*ParameterMeta       `protobuf:"bytes,3,rep,name=parameterMeta,proto3" json:"parameterMeta,omitempty"`
	Data           []float32              `protobuf:"fixed32,4,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Forecast) Reset() {
	*x = Forecast{}
	mi := &file_forecaster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forecast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forecast) ProtoMessage() {}

func (x *Forecast) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forecast.ProtoReflect.Descriptor instead.
func (*Forecast) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{2}
}

func (x *Forecast) GetForecastStatus() ForecastStatus {
	if x != nil {
		return x.ForecastStatus
	}
	return ForecastStatus_OK
}

func (x *Forecast) GetForecastMeta() *ForecastMeta {
	if x != nil {
		return x.ForecastMeta
	}
	return nil
}

func (x *Forecast) GetParameterMeta() []*ParameterMeta {
	if x != nil {
		return x.ParameterMeta
	}
	return nil
}

func (x *Forecast) GetData() []float32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type ForecastMeta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	NextUpdate    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=nextUpdate,proto3" json:"nextUpdate,omitempty"`
	GridLocation  *Location              `protobuf:"bytes,3,opt,name=GridLocation,proto3" json:"GridLocation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForecastMeta) Reset() {
	*x = ForecastMeta{}
	mi := &file_forecaster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForecastMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForecastMeta) ProtoMessage() {}

func (x *ForecastMeta) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForecastMeta.ProtoReflect.Descriptor instead.
func (*ForecastMeta) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{3}
}

func (x *ForecastMeta) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ForecastMeta) GetNextUpdate() *timestamppb.Timestamp {
	if x != nil {
		return x.NextUpdate
	}
	return nil
}

func (x *ForecastMeta) GetGridLocation() *Location {
	if x != nil {
		return x.GridLocation
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      float32                `protobuf:"fixed32,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float32                `protobuf:"fixed32,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_forecaster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{4}
}

func (x *Location) GetLatitude() float32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Location) GetLongitude() float32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type ParameterMeta struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Parameter     string                   `protobuf:"bytes,1,opt,name=parameter,proto3" json:"parameter,omitempty"`
	Units         string                   `protobuf:"bytes,2,opt,name=units,proto3" json:"units,omitempty"`
	SliceFrom     int32                    `protobuf:"varint,3,opt,name=sliceFrom,proto3" json:"sliceFrom,omitempty"`
	Times         []*timestamppb.Timestamp `protobuf:"bytes,4,rep,name=times,proto3" json:"times,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParameterMeta) Reset() {
	*x = ParameterMeta{}
	mi := &file_forecaster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParameterMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterMeta) ProtoMessage() {}

func (x *ParameterMeta) ProtoReflect() protoreflect.Message {
	mi := &file_forecaster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterMeta.ProtoReflect.Descriptor instead.
func (*ParameterMeta) Descriptor() ([]byte, []int) {
	return file_forecaster_proto_rawDescGZIP(), []int{5}
}

func (x *ParameterMeta) GetParameter() string {
	if x != nil {
		return x.Parameter
	}
	return ""
}

func (x *ParameterMeta) GetUnits() string {
	if x != nil {
		return x.Units
	}
	return ""
}

func (x *ParameterMeta) GetSliceFrom() int32 {
	if x != nil {
		return x.SliceFrom
	}
	return 0
}

func (x *ParameterMeta) GetTimes() []*timestamppb.Timestamp {
	if x != nil {
		return x.Times
	}
	return nil
}

var File_forecaster_proto protoreflect.FileDescriptor

const file_forecaster_proto_rawDesc = "" +
	"\n" +
	"\x10forecaster.proto\x12\x10internalprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\x86\x01\n" +
	"\x12GetForecastRequest\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\x126\n" +
	"\baltitude\x18\x03 \x01(\v2\x1a.internalprotocol.AltitudeR\baltitude\"<\n" +
	"\bAltitude\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x02R\x05value\x12\x1a\n" +
	"\boverride\x18\x02 \x01(\bR\boverride\"\xf3\x01\n" +
	"\bForecast\x12H\n" +
	"\x0eforecastStatus\x18\x01 \x01(\x0e2 .internalprotocol.ForecastStatusR\x0eforecastStatus\x12B\n" +
	"\fforecastMeta\x18\x02 \x01(\v2\x1e.internalprotocol.ForecastMetaR\fforecastMeta\x12E\n" +
	"\rparameterMeta\x18\x03 \x03(\v2\x1f.internalprotocol.ParameterMetaR\rparameterMeta\x12\x12\n" +
	"\x04data\x18\x04 \x03(\x02R\x04data\"\xc4\x01\n" +
	"\fForecastMeta\x128\n" +
	"\tupdatedAt\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12:\n" +
	"\n" +
	"nextUpdate\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"nextUpdate\x12>\n" +
	"\fGridLocation\x18\x03 \x01(\v2\x1a.internalprotocol.LocationR\fGridLocation\"D\n" +
	"\bLocation\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\"\x93\x01\n" +
	"\rParameterMeta\x12\x1c\n" +
	"\tparameter\x18\x01 \x01(\tR\tparameter\x12\x14\n" +
	"\x05units\x18\x02 \x01(\tR\x05units\x12\x1c\n" +
	"\tsliceFrom\x18\x03 \x01(\x05R\tsliceFrom\x120\n" +
	"\x05times\x18\x04 \x03(\v2\x1a.google.protobuf.TimestampR\x05times*B\n" +
	"\x0eForecastStatus\x12\x06\n" +
	"\x02OK\x10\x00\x12\x13\n" +
	"\x0fOutsideAllGrids\x10\x01\x12\x13\n" +
	"\x0fPointTooFarAway\x10\x022_\n" +
	"\n" +
	"Forecaster\x12Q\n" +
	"\vGetForecast\x12$.internalprotocol.GetForecastRequest\x1a\x1a.internalprotocol.Forecast\"\x00B)Z'github.com/metno/forti/internalprotocolb\x06proto3"

var (
	file_forecaster_proto_rawDescOnce sync.Once
	file_forecaster_proto_rawDescData []byte
)

func file_forecaster_proto_rawDescGZIP() []byte {
	file_forecaster_proto_rawDescOnce.Do(func() {
		file_forecaster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_forecaster_proto_rawDesc), len(file_forecaster_proto_rawDesc)))
	})
	return file_forecaster_proto_rawDescData
}

var file_forecaster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_forecaster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_forecaster_proto_goTypes = []any{
	(ForecastStatus)(0),           // 0: internalprotocol.ForecastStatus
	(*GetForecastRequest)(nil),    // 1: internalprotocol.GetForecastRequest
	(*Altitude)(nil),              // 2: internalprotocol.Altitude
	(*Forecast)(nil),              // 3: internalprotocol.Forecast
	(*ForecastMeta)(nil),          // 4: internalprotocol.ForecastMeta
	(*Location)(nil),              // 5: internalprotocol.Location
	(*ParameterMeta)(nil),         // 6: internalprotocol.ParameterMeta
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_forecaster_proto_depIdxs = []int32{
	2, // 0: internalprotocol.GetForecastRequest.altitude:type_name -> internalprotocol.Altitude
	0, // 1: internalprotocol.Forecast.forecastStatus:type_name -> internalprotocol.ForecastStatus
	4, // 2: internalprotocol.Forecast.forecastMeta:type_name -> internalprotocol.ForecastMeta
	6, // 3: internalprotocol.Forecast.parameterMeta:type_name -> internalprotocol.ParameterMeta
	7, // 4: internalprotocol.ForecastMeta.updatedAt:type_name -> google.protobuf.Timestamp
	7, // 5: internalprotocol.ForecastMeta.nextUpdate:type_name -> google.protobuf.Timestamp
	5, // 6: internalprotocol.ForecastMeta.GridLocation:type_name -> internalprotocol.Location
	7, // 7: internalprotocol.ParameterMeta.times:type_name -> google.protobuf.Timestamp
	1, // 8: internalprotocol.Forecaster.GetForecast:input_type -> internalprotocol.GetForecastRequest
	3, // 9: internalprotocol.Forecaster.GetForecast:output_type -> internalprotocol.Forecast
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_forecaster_proto_init() }
func file_forecaster_proto_init() {
	if File_forecaster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_forecaster_proto_rawDesc), len(file_forecaster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_forecaster_proto_goTypes,
		DependencyIndexes: file_forecaster_proto_depIdxs,
		EnumInfos:         file_forecaster_proto_enumTypes,
		MessageInfos:      file_forecaster_proto_msgTypes,
	}.Build()
	File_forecaster_proto = out.File
	file_forecaster_proto_goTypes = nil
	file_forecaster_proto_depIdxs = nil
}
