// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package internalprotocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// ForecasterClient is the client API for Forecaster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForecasterClient interface {
	GetForecast(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Forecast, error)
}

type forecasterClient struct {
	cc grpc.ClientConnInterface
}

func NewForecasterClient(cc grpc.ClientConnInterface) ForecasterClient {
	return &forecasterClient{cc}
}

func (c *forecasterClient) GetForecast(ctx context.Context, in *Location, opts ...grpc.CallOption) (*Forecast, error) {
	out := new(Forecast)
	err := c.cc.Invoke(ctx, "/internalprotocol.Forecaster/GetForecast", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForecasterServer is the server API for Forecaster service.
// All implementations must embed UnimplementedForecasterServer
// for forward compatibility
type ForecasterServer interface {
	GetForecast(context.Context, *Location) (*Forecast, error)
	mustEmbedUnimplementedForecasterServer()
}

// UnimplementedForecasterServer must be embedded to have forward compatible implementations.
type UnimplementedForecasterServer struct {
}

func (UnimplementedForecasterServer) GetForecast(context.Context, *Location) (*Forecast, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetForecast not implemented")
}
func (UnimplementedForecasterServer) mustEmbedUnimplementedForecasterServer() {}

// UnsafeForecasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForecasterServer will
// result in compilation errors.
type UnsafeForecasterServer interface {
	mustEmbedUnimplementedForecasterServer()
}

func RegisterForecasterServer(s grpc.ServiceRegistrar, srv ForecasterServer) {
	s.RegisterService(&_Forecaster_serviceDesc, srv)
}

func _Forecaster_GetForecast_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Location)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForecasterServer).GetForecast(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/internalprotocol.Forecaster/GetForecast",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForecasterServer).GetForecast(ctx, req.(*Location))
	}
	return interceptor(ctx, in, info, handler)
}

var _Forecaster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "internalprotocol.Forecaster",
	HandlerType: (*ForecasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetForecast",
			Handler:    _Forecaster_GetForecast_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "forecaster.proto",
}
